name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm production deployment'
        required: true
        default: 'no'

jobs:
  validate:
    name: Validate Deployment
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Check confirmation
        if: github.event.inputs.confirm != 'yes'
        run: |
          echo "Production deployment not confirmed. Please run the workflow again with confirmation."
          exit 1

  deploy-backend:
    name: Deploy Backend Services
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'yes')
    strategy:
      matrix:
        service:
          - backend/auth_service
          - backend/user_service
          - backend/patient_service
          - backend/schedule_service
          - backend/api_gateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ${{ matrix.service }}/package-lock.json

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm ci

      - name: Build
        run: |
          cd ${{ matrix.service }}
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract service name
        id: extract_service
        run: echo "SERVICE_NAME=$(echo ${{ matrix.service }} | awk -F/ '{print $NF}')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            drassistant/${{ steps.extract_service.outputs.SERVICE_NAME }}:prod-${{ github.sha }}
            drassistant/${{ steps.extract_service.outputs.SERVICE_NAME }}:latest

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: [validate, deploy-backend]
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'yes')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/web/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend/web
          npm ci

      - name: Build
        run: |
          cd frontend/web
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/web
          file: ./frontend/web/Dockerfile
          push: true
          tags: |
            drassistant/frontend-web:prod-${{ github.sha }}
            drassistant/frontend-web:latest

  deploy-to-prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.PROD_KNOWN_HOSTS }}
          
      - name: Deploy to production server
        run: |
          echo "Deploying to production server..."
          ssh ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} << 'EOF'
            cd /opt/dr-assistant
            
            # Pull the latest docker-compose file
            git pull
            
            # Update the image tags in docker-compose.yml
            sed -i "s|drassistant/auth_service:.*|drassistant/auth_service:prod-${{ github.sha }}|g" docker-compose.prod.yml
            sed -i "s|drassistant/user_service:.*|drassistant/user_service:prod-${{ github.sha }}|g" docker-compose.prod.yml
            sed -i "s|drassistant/patient_service:.*|drassistant/patient_service:prod-${{ github.sha }}|g" docker-compose.prod.yml
            sed -i "s|drassistant/schedule_service:.*|drassistant/schedule_service:prod-${{ github.sha }}|g" docker-compose.prod.yml
            sed -i "s|drassistant/api_gateway:.*|drassistant/api_gateway:prod-${{ github.sha }}|g" docker-compose.prod.yml
            sed -i "s|drassistant/frontend-web:.*|drassistant/frontend-web:prod-${{ github.sha }}|g" docker-compose.prod.yml
            
            # Pull the latest images
            docker-compose -f docker-compose.prod.yml pull
            
            # Restart the services
            docker-compose -f docker-compose.prod.yml up -d
          EOF
          
      - name: Notify deployment status
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_TITLE: Production Deployment
          SLACK_MESSAGE: 'Successfully deployed to production environment :rocket:'
          SLACK_COLOR: good
